---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-sample
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
