name: jenkinstest
namespaceOverride: jenkinstest
controller:
  adminPassword: Example2!
  serviceType: LoadBalancer

#persistence:
#  volumes:
#  - type: HostPath
#    hostPath: /var/run/docker.sock
#    mountPath: /var/run/docker.sock
